[project]
name = "cat-ricias"
version = "1.0.0"
description = "Acaricia o llora"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "flet[all]>=0.28.3",
    "flet-audio==0.1.0",
]
